#!/bin/sh
#
# This hook runs ktlint and rejects commit, if there are any formatting errors.
# If ktlint is not installed, user will be prompted to install it.

#  define red, green and no_color
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "pre-commit: ${GREEN}Checking for ktlint...${NC}"
ktlint --version || {
    echo "pre-commit: ${RED}ktlint not found! Please install it.${NC}"
    exit 1
}
# Run ktlint
ktlint || {
    echo "pre-commit: ${RED}ktlint found errors, please fix them.\n  Try 'ktlint -F'${NC}"
    exit 1
}
echo "pre-commit: ${GREEN}ktlint passed!${NC}"
exit 0
