name: lint_kotlin
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # from the ktlint wiki page https://pinterest.github.io/ktlint/0.49.0/install/cli/
            - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.49.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
            - run: ktlint